liip_imagine:
    driver: "gd"
    cache: default_uploads

    resolvers:
        default_uploads:
            flysystem:
                filesystem_service: oneup_flysystem.default_uploads_filesystem
                root_url:           "http://localhost:8000/images/uploads"
                cache_prefix:       media/cache
                visibility:         public
#        default:
#            web_path:
#                web_root: "%kernel.project_dir%/public"
#                cache_prefix: "images/cache"

    loaders:
        default_uploads:
            flysystem:
                filesystem_service: oneup_flysystem.default_uploads_filesystem

    data_loader: default_uploads
#            filesystem:
#                data_root: "%kernel.project_dir%/public/"

    filter_sets:
        squared_thumbnail:
            jpeg_quality:          85
            png_compression_level: 8
            filters:
                auto_rotate: ~
                strip: ~
                thumbnail:
                    size:          [50, 50]
                    mode:          outbound
                    allow_upscale: true
                background:
                    size:     [55, 55]
                    position: center
                    color:    '#ccc'
