# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_uploads:
            awss3v3:
                client: acme.s3_client
                bucket: "%env(resolve:AWS_BUCKET)%"
                prefix: 'uploads'

#            local:
#                directory: '%kernel.project_dir%/public/images/new_uploads'
    filesystems:
        default_uploads:
            adapter: default_uploads
            alias: League\Flysystem\Filesystem
            mount: default_uploads
            visibility: public
