# Read the documentation: https://github.com/1up-lab/OneupFlysystemBundle/tree/master/Resources/doc/index.md
oneup_flysystem:
    adapters:
        default_uploads:
            local:
                directory: '%kernel.project_dir%/public/images/uploads'
    filesystems:
        default_uploads:
            adapter: default_uploads
            alias: League\Flysystem\Filesystem
            mount: default_uploads

