vich_uploader:
    db_driver: orm
    storage: flysystem

    mappings:
        uploads:
            uri_prefix: /images/uploads
            upload_destination: default_uploads
#            upload_destination: '%kernel.project_dir%/public/images/uploads'
            namer: App\Naming\ImageNamer
